version: "3"

services:
  webserver:
    build:
      context: ./bin/php8
    container_name: "lamp-php8"
    restart: "always"
    ports:
      - "18018:80"
      - "14343:443"
    links:
      - database
    volumes:
      - /home/local/lamp:/var/www/html:rw
      - /home/local/lamp/config/php/php.ini:/usr/local/etc/php/php.ini
      - /home/local/lamp/config/ssl:/etc/apache2/ssl/
      - /home/local/lamp/config/vhosts:/etc/apache2/sites-enabled
      - /home/local/lamp/logs/apache2:/var/log/apache2
      - /home/local/lamp/logs/xdebug:/var/log/xdebug
    environment:
      APACHE_DOCUMENT_ROOT: /home/local/lamp/www
      PMA_PORT: 23306
      MYSQL_ROOT_PASSWORD: Piggy$4321
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: docker
      HOST_MACHINE_MYSQL_PORT: 33306
      XDEBUG_CONFIG: "client_host=host.docker.internal remote_port=19003"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  database:
    build:
      context: "./bin/mysql8"
    container_name: "lamp-mysql8"
    restart: "always"
    ports:
      - "127.0.0.1:13313:3306"
    volumes:
      - /home/local/lamp/config/initdb:/docker-entrypoint-initdb.d
      - /home/local/lamp/data/mysql:/var/lib/mysql
      - /home/local/lamp/logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Piggy$4321
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
  phpmyadmin:
    image: phpmyadmin
    container_name: "lamp-phpmyadmin"
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: Piggy$4321
      MYSQL_ROOT_PASSWORD: Piggy$4321
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      UPLOAD_LIMIT: 512M
      MEMORY_LIMIT: 512M
    ports:
      - "43306:80"
      - "43307:443"
    volumes:
      - /sessions
      - /home/local/lamp/config/php/php.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
  redis:
    container_name: "lamp-redis"
    image: redis:latest
    ports:
      - "127.0.0.1:16379:6379"
